# Generated by Django 4.0.5 on 2022-06-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_member', to='content.neighborhood', verbose_name='NeighbourHood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.profile', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Memberships',
            },
        ),
    ]
