# Generated by Django 4.0.5 on 2022-06-19 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='admin',
            new_name='hood_admin',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=150, null=True, verbose_name='Bio'),
        ),
    ]
