# Generated by Django 4.0.5 on 2022-06-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_admin_neighborhood_hood_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Title'),
        ),
    ]
