# Generated by Django 4.0.5 on 2022-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Neighborhood Name'),
        ),
    ]
